<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/header.phtml'); ?>
<div class="container">

	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">新建用户</h3>
	  </div>
	
	<form class="form-horizontal" method="post" role="form" id="addform">
	  <div class="panel-body">
		
		    <div class="form-group">
			<label class="col-sm-2 control-label">用户名:</label>
			<div class="col-sm-4">
			    <input id="username" class="form-control" type="text" name="username">
			</div>
		    </div>

		    <div class="form-group">
			<label class="col-sm-2 control-label">用户昵称:</label>
			<div class="col-sm-4">
			    <input id="nick" class="form-control" type="text" name="nick">
			</div>    
		    </div>
	  </div>
		
		<div class="panel-footer">
			<button class="btn btn-sm btn-primary " type="button" id="save" >保存</button>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<a class="btn btn-sm btn-primary " href="/user/list">返回</a>
		</div>
	</form>
	</div>
</div>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/modal.phtml'); ?>
<script>

$("button#save").click(function(){

    if ( $("#srcaddr").val() == "" ) {
        mymodal.notice("user name can't be empty", "", "", "300px");
        return;
    }
    
    //start post data
    $.post('/user/add', $("form#addform").serialize(), function(data){
        if (data.rst == 1) {
		location.href="/user/list";
            //mymodal.refresh("deploy completed", location.href, "", "", "300px");
        } else if( data.errno ) {
            mymodal.notice(data.errmsg, "", "", "300px");
        }
    });
    
});
</script>
<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/footer.phtml'); ?>
