<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/header.phtml'); ?>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/diff.phtml'); ?>

<form class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-2 control-label" title="文件1">文件1</label>
        <div class="col-sm-10">
        <input name="f1" value="" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" title="文件2">文件2</label>
        <div class="col-sm-10">
        <input name="f2" value="" />
        </div>
    </div>
<hr>
    <div class="form-group text-center">
        <button type="submit" class="btn btn-danger">比较</button>
    </div>
</form>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/modal.phtml'); ?>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/footer.phtml'); ?>
