<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/header.phtml'); ?>

<div class="container">
<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/diff.phtml'); ?>

<hr/>
<form class="form-horizontal" method="post">
    <div class="form-group">
        <div class="col-sm-6">
        <textarea class="form-control" rows="30" name="c1"><?=$c1?></textarea>
        </div>
        <div class="col-sm-6">
        <textarea class="form-control" rows="30" name="c2"><?=$c2?></textarea>
        </div>
    </div>
<hr>
    <div class="form-group text-center">
        <button type="submit" class="btn btn-danger">比较</button>
    </div>
</form>
</div>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/modal.phtml'); ?>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/footer.phtml'); ?>
