<form class="form-horizontal" role="form" method="post" action="<?=empty($action_url) ? '' : $action_url?>">

    <?php if(!empty($partnerid) && !empty($action) && $action == "edit")://如果是编辑页，则需要加一些按钮?>
    <div class="form-group text-center">
        <button type="button" class="btn btn-danger" data-toggle="mymodal" data-title="确认删除" data-content='确认删除这个业务码么<?=$partnerid?>??' data-url="/page/del" data-field='{"partnerid":"<?=$partnerid?>"}'>删除此业务</button>
    </div>
    <?php endif; ?>

    <hr/>
    <div class="form-group">
        <label class="col-sm-2 control-label" title="业务码">业务码</label>
        <div class="col-sm-10">
        <input name="partnerid" value="<?=empty($partnerid) ? '' : $partnerid?>" title="业务号" type="text" class="form-control"  placeholder="业务码" <?= (!empty($action) && $action == 'edit') ? 'readonly' : ''?> >
        </div>
    </div>

    <hr id="TAG_form_input_end"/>
    <div class="form-group">
        <label class="col-sm-2 control-label" title="">添加字段</label>
        <div class="col-sm-10">
            <div class="input-group" id="addkeyarea">
                <input autocomplete='off' id="addkey" type="text" class="form-control" placeholder="输入字段名，多层以-分隔">
                <ul class="dropdown-menu" role="menu" id="addkeydropdown">
                </ul>
                <span class="input-group-btn">
                    <button class="btn btn-success" type="button">添加</button>
                </span>
            </div>
        </div>
    </div>

    <hr/>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" data-toggle="ajaxsubmit">提交</button>
        </div>
    </div>
</form>
<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/modal.phtml'); ?>
<script src="/js/page.js"></script>
<script>
            var partnerid = '<?= $partnerid?>';
            var partner_info = <?=json_encode($partner_info)?>;
            var partner_desc = <?=json_encode($partner_desc)?>;
            var hosts = <?=json_encode($hosts)?>;
            var field_avail = <?=json_encode($field_avail)?>;

            //填充页面
            page.init_form_area(partner_info);

            $("#addkey").keyup(function(){
                //当用户填写添加字段的input框的时候，触发这个事件
                $("#addkeydropdown").html(page.gen_add_dropdown_by_input($(this).val()));
            }).focus(function(){
                $(this).keyup();
                $("#addkeydropdown").show();
            }).focusout(function(){
                $("#addkeydropdown").hide('fast');
            });
            $("#addkeyarea button").click(function(){
                key = $("#addkey").val();
                if(key == ''){
                    mymodal.notice("请填写相关字段名称");
                }else if(partner_info[key] != undefined){
                    mymodal.notice("已经存在这个字段了, 可以直接修改");
                }else{
                    delete(field_avail[key]);
                    page.insert_form_input(key, "", true);
                    $("#addkey").val("");
                }
            })
</script>

