<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/header.phtml'); ?>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/diff.phtml'); ?>
<form class="form-horizontal" role="form" method="post" action="<?=empty($action_url) ? '' : $action_url?>">

<hr>
    <div class="form-group text-center">
        <button type="button" class="btn btn-danger" data-toggle="mymodal" data-title="确认提交" data-content='确认提交这些修改么，提交将发布到线上' data-url="/page/publish" data-field='{"online":"1"}'>确认提交修改</button>
    </div>
</form>
<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/modal.phtml'); ?>

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/footer.phtml'); ?>
