<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/header.phtml'); ?>

<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-3 col-sm-2 sidebar-offcanvas" id="sidebar" role="navigation">
            <form role="form" action="/page/show">
                <div class="input-group">
                    <input placeholder="输入业务码" type="text" class="form-control" name="partnerid">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div><!-- /input-group -->
            </form>
            <br/>
            <div class="list-group">
                <?php foreach($partners as $k => $v){ ?>
                <a href="/page/show?partnerid=<?=$k?>" class="list-group-item<?= (!empty($partnerid) && $k == $partnerid) ? " active" : "";?>"><?=$k?></a>
                <?php } ?>
            </div>
        </div>


        <div class="col-xs-15 col-sm-10">
            <?php Yaf_Loader::import(dirname(__FILE__) . '/../include/box.phtml'); ?>

            <?php Yaf_Loader::import(dirname(__FILE__) . '/c_edit.phtml');?>
        </div>

    </div>
</div><!--/.container-->

<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/footer.phtml'); ?>
