<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/header.phtml'); ?>

<div class="container">
    <div class="starter-template">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div>

</div><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->


<?php Yaf_Loader::import(dirname(__FILE__) . '/../include/footer.phtml'); ?>
