<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?= $title ?></title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/my.css" rel="stylesheet">
        <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/common.js"></script>

    </head>
    <body>
        <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">管理</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach($navs as $k => $v){ 
                            if(empty(${$k . "Navs"})){
                        ?>
                            <li class="<?= $controllerName == $k ? "active " : ""; ?>">
                                <a href="/<?= $k ?>"><?= $v ?></a></li>
                        <?php }else{ ?>
                        <li class="<?= $controllerName == $k ? "active " : ""; ?> dropdown ">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <?= $v ?><span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <?php foreach(${$k . "Navs"} as $kk => $vv){?>
                                <li class="<?= $actionName == $kk ? "active " : "";?>">
                                <a href="/<?= $k . "/" . $kk?>"><?= $vv ?></a></li>
                                <?php } ?>
                            </ul>
                        </li>
                        <?php }} ?>
                    </ul>
				  	<ul class="nav navbar-nav navbar-right">
						<li id="userli"><a>Hi, <?=$user['nick']?></a></li>
						<li id="logoutli"><a href="/user/logout">退出</a></li>
				  	</ul>
                </div><!-- /.nav-collapse -->
            </div><!-- /.container -->
        </div><!-- /.navbar -->

